# Generated by Django 4.1.5 on 2023-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AddField(
            model_name='answer',
            name='is_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
